#!/usr/bin/python

def reverse(a_to_b):
    b_to_a = {}
    for a in a_to_b:
        b = a_to_b[a]
        b_to_a[b] = a
    return b_to_a

def print_dict(dict):
    for item in dict:
        print item, dict[item]


names = {
    'H':  'hydrogen',
    'He': 'helium',
    'Li': 'lithium',
    'Be': 'beryllium',
    'B':  'boron',
    'C':  'carbon',
    'N':  'nitrogen',
    'O':  'oxygen',
    'F':  'fluorine',
    'Ne': 'neon',
    'Na': 'sodium',
    'Mg': 'magnesium',
    'Al': 'aluminium',
    'Si': 'silicon',
    'P':  'phosphorus',
    'S':  'sulphur',
    'Cl': 'chlorine',
    'Ar': 'argon',
    'K':  'potassium',
    'Ca': 'calcium',
    'Sc': 'scandium',
    'Ti': 'titanium',
    'V':  'vanadium',
    'Cr': 'chromium',
    'Mn': 'manganese',
    'Fe': 'iron',
    'Co': 'cobalt',
    'Ni': 'nickel',
    'Cu': 'copper',
    'Zn': 'zinc',
    'Ga': 'gallium',
    'Ge': 'germanium',
    'As': 'arsenic',
    'Se': 'selenium',
    'Br': 'bromine',
    'Kr': 'krypton',
    'Rb': 'rubidium',
    'Sr': 'strontium',
    'Y':  'yttrium',
    'Zr': 'zirconium',
    'Nb': 'niobium',
    'Mo': 'molybdenum',
    'Tc': 'technetium',
    'Ru': 'ruthenium',
    'Rh': 'rhodium',
    'Pd': 'palladium',
    'Ag': 'silver',
    'Cd': 'cadmium',
    'In': 'indium',
    'Sn': 'tin',
    'Sb': 'antimony',
    'Te': 'tellurium',
    'I':  'iodine',
    'Xe': 'xenon',
    'Cs': 'caesium',
    'Ba': 'barium,',
    'La': 'lanthanum',
    'Ce': 'cerium',
    'Pr': 'praesodymium',
    'Nd': 'neodymium',
    'Pm': 'promethium',
    'Sm': 'samarium',
    'Eu': 'europium',
    'Gd': 'gadolinium',
    'Tb': 'terbium',
    'Dy': 'dysprosium',
    'Ho': 'holmium',
    'Er': 'erbium',
    'Tm': 'thulium',
    'Yb': 'ytterbium',
    'Lu': 'lutetium',
    'Hf': 'hafnium',
    'Ta': 'tantalum',
    'W':  'tungsten',
    'Re': 'rhenium',
    'Os': 'osmium',
    'Ir': 'iridium',
    'Pt': 'platinum',
    'Au': 'gold',
    'Hg': 'mercury',
    'Tl': 'thallium',
    'Pb': 'lead',
    'Bi': 'bismuth',
    'Po': 'polonium',
    'At': 'astatine',
    'Rn': 'radon',
    'Fr': 'francium',
    'Ra': 'radium',
    'Ac': 'actinium',
    'Th': 'thorium',
    'Pa': 'protactinium',
    'U':  'uranium',
    }

symbols = reverse(names)
print_dict(symbols)
